/* Bloodwood Bowmen: True Draw */
const BUILD_ID = "bloodwood-bowmen-v20260620-0017-true-draw";
const LEVELS = [
  {name:"Cedar Warm-Up", mode:"targets", wind:0.004, targets:[{x:690,y:.63,r:34,hp:2},{x:820,y:.53,r:28,hp:2},{x:960,y:.67,r:36,hp:3}]},
  {name:"Quarry Apples", mode:"targets", wind:-0.012, targets:[{x:720,y:.64,r:42,hp:4},{x:920,y:.46,r:30,hp:3},{x:1110,y:.68,r:34,hp:4},{x:1240,y:.54,r:26,hp:3}]},
  {name:"Low Hill Duel", mode:"duel", wind:0.016, enemy:{x:980,skill:.40,hp:3,name:"Rafe Holt"}, targets:[{x:820,y:.62,r:24,hp:2},{x:1110,y:.56,r:26,hp:2}]},
  {name:"Broken Orchard", mode:"duel", wind:-0.024, enemy:{x:1080,skill:.58,hp:4,name:"Mara Voss"}, targets:[{x:770,y:.56,r:28,hp:3},{x:930,y:.69,r:26,hp:3},{x:1210,y:.50,r:24,hp:3}]},
  {name:"Rainline Champion", mode:"duel", wind:0.028, enemy:{x:1160,skill:.74,hp:5,name:"Ilan Greaves"}, targets:[{x:900,y:.47,r:24,hp:3},{x:1030,y:.65,r:28,hp:3}]},
  {name:"Bloodwood Final", mode:"duel", wind:-0.034, enemy:{x:1250,skill:.88,hp:6,name:"The Yew King"}, targets:[{x:860,y:.58,r:26,hp:4},{x:1110,y:.45,r:24,hp:4},{x:1340,y:.66,r:30,hp:4}]}
];
const canvas = document.getElementById('game');
const ctx = canvas.getContext('2d');
const $ = id => document.getElementById(id);
const menuButton=$('menuButton'), menuPanel=$('menuPanel'), levelGrid=$('levelGrid');
const state = { level:0, zoom:1, cameraX:0, dragging:false, dragStart:null, dragNow:null, arrows:[], fragments:[], shocks:[], turn:'player', shots:0, last:0, notice:'', noticeUntil:0, aiQueued:false, levelComplete:false };
let dpr=1,W=0,H=0,groundY=0,player,enemy,targets=[];
const telemetry = (()=>{ const sid = crypto.randomUUID(); const q=[]; function rec(type,data={}){ const evt={buildId:BUILD_ID,sessionId:sid,t:new Date().toISOString(),ms:Math.round(performance.now()),type,level:state.level,turn:state.turn,data}; q.push(evt); try{localStorage.setItem('bloodwood.telemetry',JSON.stringify(q.slice(-3000)))}catch{}; try{navigator.sendBeacon&&navigator.sendBeacon('/api/log',new Blob([JSON.stringify(evt)+'\n'],{type:'application/x-ndjson'}));}catch{} } addEventListener('error',e=>rec('window.error',{message:e.message,source:e.filename,line:e.lineno,col:e.colno})); addEventListener('unhandledrejection',e=>rec('promise.rejection',{reason:String(e.reason)})); return {rec,dump:()=>q.slice(),sid}; })();
telemetry.rec('boot',{ua:navigator.userAgent,viewport:[innerWidth,innerHeight],standalone:matchMedia('(display-mode: standalone)').matches});
function resize(){ dpr=Math.min(devicePixelRatio||1,2.5); W=innerWidth; H=innerHeight; canvas.width=Math.floor(W*dpr); canvas.height=Math.floor(H*dpr); ctx.setTransform(dpr,0,0,dpr,0,0); groundY=Math.max(250,H*.76); if(player){player.y=groundY-58} if(enemy){enemy.y=groundY-58} targets.forEach(t=>t.y=targetY(t)); telemetry.rec('resize',{W,H,dpr}); }
addEventListener('resize',resize); resize();
function targetY(t){ return typeof t.ySpec==='number' ? Math.round(H*t.ySpec) : t.y; }
function makeLevels(){ levelGrid.innerHTML=''; LEVELS.forEach((L,i)=>{ const b=document.createElement('button'); b.className='levelBtn'; b.innerHTML=`<small>${String(i+1).padStart(2,'0')} · ${L.mode}</small><span>${L.name}</span>`; b.onclick=()=>{loadLevel(i); closeMenu();}; levelGrid.appendChild(b); }); }
function updateLevelButtons(){ [...levelGrid.children].forEach((b,i)=>b.classList.toggle('active',i===state.level)); }
function loadLevel(i){ const L=LEVELS[(i+LEVELS.length)%LEVELS.length]; state.level=(i+LEVELS.length)%LEVELS.length; state.arrows=[]; state.fragments=[]; state.shocks=[]; state.turn='player'; state.shots=0; state.aiQueued=false; state.levelComplete=false; player={x:145,y:groundY-58,hp:5,maxHp:5,name:'You',stance:0}; enemy=L.enemy?{x:L.enemy.x,y:groundY-58,hp:L.enemy.hp,maxHp:L.enemy.hp,skill:L.enemy.skill,name:L.enemy.name,stance:0}:null; targets=L.targets.map((t,k)=>({...t,ySpec:t.y,y:Math.round(H*t.y),maxHp:t.hp,id:`L${state.level}-T${k}`,alive:true,boom:0})); state.cameraX=0; state.zoom=1; flash(`${L.name}`); updateLevelButtons(); telemetry.rec('level.load',{index:state.level,level:L}); }
function flash(text){ state.notice=text; state.noticeUntil=performance.now()+1200; telemetry.rec('notice',{text}); }
makeLevels(); loadLevel(0);
function wx(x){return (x-state.cameraX)*state.zoom} function wy(y){return y*state.zoom+(H-H*state.zoom)*.5} function sx(x){return x/state.zoom+state.cameraX} function sy(y){return (y-(H-H*state.zoom)*.5)/state.zoom}
function line(a,b,c,d){ctx.beginPath();ctx.moveTo(a,b);ctx.lineTo(c,d);ctx.stroke()} function blob(x,y,w,h,rot=0){ctx.beginPath();ctx.ellipse(x,y,w,h,rot,0,Math.PI*2);ctx.fill()} function dist(a,t){return Math.hypot(a.x-t.x,a.y-t.y)}
function loop(ts){ const dt=Math.min(34,ts-state.last||16)/16; state.last=ts; update(dt); draw(ts); requestAnimationFrame(loop); } requestAnimationFrame(loop);
function update(dt){ const L=LEVELS[state.level]; for(const a of state.arrows){ if(a.dead)continue; a.vx+=L.wind*dt; a.vy+=.335*dt; a.x+=a.vx*dt; a.y+=a.vy*dt; if(a.y>groundY-4) hitGround(a); for(const t of targets){ if(!a.dead && t.alive && dist(a,t)<t.r){ damageTarget(t,a); a.dead=true; }} if(enemy && !a.dead && a.owner==='player' && Math.hypot(a.x-enemy.x,a.y-(enemy.y-36))<34){ damageBowman(enemy,a); a.dead=true; } if(!a.dead && a.owner==='enemy' && Math.hypot(a.x-player.x,a.y-(player.y-36))<34){ damageBowman(player,a); a.dead=true; }} state.arrows=state.arrows.filter(a=>!a.dead && a.x>-300 && a.x<1800 && a.y<1200); for(const p of state.fragments){ p.vy+=.19*dt; p.x+=p.vx*dt; p.y+=p.vy*dt; p.spin+=p.rs*dt; p.life-=dt; } state.fragments=state.fragments.filter(p=>p.life>0); for(const s of state.shocks)s.life-=dt; state.shocks=state.shocks.filter(s=>s.life>0); if(enemy&&state.turn==='enemy'&&!state.aiQueued&&state.arrows.length===0){ state.aiQueued=true; setTimeout(enemyShoot,420); }}
function draw(ts){ ctx.clearRect(0,0,W,H); drawWorld(ts); drawRangeMarks(); targets.forEach(t=>drawTarget(t,ts)); drawArcher(player,true,ts); if(enemy) drawArcher(enemy,false,ts); state.arrows.forEach(drawArrow); state.fragments.forEach(drawFragment); state.shocks.forEach(drawShock); if(state.dragging) drawAim(); drawMinimalHUD(ts); }
function drawWorld(ts){ const sky=ctx.createLinearGradient(0,0,0,H); sky.addColorStop(0,'#788b94'); sky.addColorStop(.48,'#b7aa86'); sky.addColorStop(.66,'#6e7c44'); sky.addColorStop(1,'#24140d'); ctx.fillStyle=sky; ctx.fillRect(0,0,W,H); ctx.globalAlpha=.23; ctx.fillStyle='#fff3d8'; for(let i=-1;i<7;i++) blob(wx(i*300+70),wy(70+(i%3)*34),80,22); ctx.globalAlpha=1; ctx.fillStyle='#31411f'; for(let x=-200;x<1700;x+=95){ const h=50+30*Math.sin(x*.013); ctx.fillRect(wx(x),wy(groundY-h),wx(48)-wx(0),h*state.zoom); } const g=wy(groundY); ctx.fillStyle='#3a2617'; ctx.fillRect(0,g,W,H-g); ctx.fillStyle='#27170e'; for(let x=-200;x<1700;x+=60) ctx.fillRect(wx(x),g-4,38*state.zoom,8); ctx.fillStyle='rgba(0,0,0,.28)'; ctx.fillRect(0,g, W, 16*state.zoom); }
function drawRangeMarks(){ ctx.save(); ctx.globalAlpha=.32; ctx.strokeStyle='#e6d0a8'; ctx.lineWidth=1; for(let x=200;x<1500;x+=100){ line(wx(x),wy(groundY),wx(x),wy(groundY+8)); } ctx.restore(); }
function drawArcher(b,isPlayer,ts){ const x=wx(b.x), y=wy(b.y); const scale=state.zoom*(isPlayer?1:1.03); ctx.save(); ctx.translate(x,y); if(!isPlayer) ctx.scale(-1,1); ctx.scale(scale,scale); const breath=Math.sin(ts/430+b.x)*1.3; ctx.lineCap='round'; ctx.lineJoin='round'; ctx.fillStyle='rgba(0,0,0,.30)'; blob(0,12,44,10); ctx.strokeStyle='#2a1710'; ctx.lineWidth=8; line(-7,-42+breath,-11,-4); line(11,-42+breath,8,-4); ctx.strokeStyle='#594130'; ctx.lineWidth=9; line(-10,-5,-26,44); line(8,-5,22,44); ctx.strokeStyle='#21140f'; ctx.lineWidth=6; line(-26,44,-36,47); line(22,44,34,46); ctx.fillStyle=isPlayer?'#6b4d31':'#4f4039'; ctx.beginPath(); ctx.moveTo(-20,-56+breath); ctx.quadraticCurveTo(0,-76+breath,22,-55+breath); ctx.lineTo(16,-9); ctx.quadraticCurveTo(0,2,-18,-9); ctx.closePath(); ctx.fill(); ctx.fillStyle=isPlayer?'#c99a6b':'#9b6f5f'; blob(0,-85+breath,13,16); ctx.fillStyle='#2c2118'; blob(0,-98+breath,15,7,.15); ctx.strokeStyle='#36251b'; ctx.lineWidth=7; line(-12,-48+breath,-42,-33); line(15,-47+breath,35,-35); ctx.strokeStyle='#b48649'; ctx.lineWidth=4; ctx.beginPath(); ctx.arc(44,-32,43,-1.34,1.34); ctx.stroke(); ctx.strokeStyle='rgba(255,241,210,.86)'; ctx.lineWidth=1.5; line(54,-72,54,8); ctx.fillStyle='#8b1714'; for(let i=0;i<b.hp;i++) blob(-30+i*11,-118,4.4,5.4); ctx.restore(); }
function drawTarget(t,ts){ if(!t.alive)return; const x=wx(t.x), y=wy(t.y), r=t.r*state.zoom; const frac=t.hp/t.maxHp; ctx.save(); ctx.translate(x,y); ctx.rotate(Math.sin(ts/380+t.x)*.025 + (1-frac)*.08); ctx.fillStyle='#4a2a17'; ctx.fillRect(-r*.12,r*.72,r*.24,wy(groundY)-y-r*.72); ctx.fillStyle='#452616'; blob(0,0,r*1.08,r*1.08); ctx.fillStyle=`hsl(${38+frac*72},55%,${34+frac*19}%)`; blob(0,0,r*.92,r*.92); ctx.fillStyle='#eee0bc'; blob(0,0,r*.62,r*.62); ctx.fillStyle='#842018'; blob(0,0,r*.32,r*.32); ctx.strokeStyle='rgba(20,8,3,.75)'; ctx.lineWidth=2.4; for(let i=0;i<t.maxHp-t.hp;i++){ line(-r*.72+i*r*.20,-r*.38,r*.16+i*r*.08,r*.54); } ctx.restore(); }
function drawArrow(a){ ctx.save(); ctx.translate(wx(a.x),wy(a.y)); ctx.rotate(Math.atan2(a.vy,a.vx)); ctx.strokeStyle='#3a2415'; ctx.lineWidth=Math.max(2,3*state.zoom); line(-20*state.zoom,0,18*state.zoom,0); ctx.fillStyle='#d8d0bd'; ctx.beginPath(); ctx.moveTo(20*state.zoom,0); ctx.lineTo(8*state.zoom,-5*state.zoom); ctx.lineTo(8*state.zoom,5*state.zoom); ctx.closePath(); ctx.fill(); ctx.fillStyle=a.owner==='player'?'#f0c264':'#ac8ee8'; ctx.fillRect(-21*state.zoom,-3*state.zoom,8*state.zoom,6*state.zoom); ctx.restore(); }
function drawFragment(p){ ctx.save(); ctx.translate(wx(p.x),wy(p.y)); ctx.rotate(p.spin); ctx.globalAlpha=Math.max(0,p.life/p.max); ctx.fillStyle=p.color; blob(0,0,p.r*state.zoom,p.r*.62*state.zoom); ctx.restore(); ctx.globalAlpha=1; }
function drawShock(s){ ctx.save(); ctx.globalAlpha=Math.max(0,s.life/s.max); ctx.strokeStyle=s.color; ctx.lineWidth=3*state.zoom; ctx.beginPath(); ctx.arc(wx(s.x),wy(s.y),(s.max-s.life)*s.r*state.zoom,0,Math.PI*2); ctx.stroke(); ctx.restore(); ctx.globalAlpha=1; }
function drawAim(){ const start={x:wx(player.x+44),y:wy(player.y-36)}, cur=state.dragNow; const dx=start.x-cur.x, dy=start.y-cur.y; ctx.save(); ctx.strokeStyle='rgba(255,240,190,.82)'; ctx.lineWidth=3; ctx.setLineDash([10,9]); line(start.x,start.y,start.x+dx*1.2,start.y+dy*1.2); ctx.setLineDash([]); ctx.fillStyle='rgba(230,180,78,.9)'; blob(cur.x,cur.y,9,9); ctx.restore(); }
function drawMinimalHUD(ts){ const L=LEVELS[state.level]; ctx.save(); ctx.globalAlpha=.8; ctx.fillStyle='rgba(0,0,0,.25)'; blob(W-58,H-42,38,16); ctx.strokeStyle='#e7c277'; ctx.lineWidth=3; line(W-78,H-42,W-38,H-42); const dir=L.wind>=0?1:-1; line(W-58+dir*18,H-48,W-38+dir*0,H-42); ctx.globalAlpha=1; ctx.restore(); }
function explode(x,y,power=1,label='target'){ state.shocks.push({x,y,life:34,max:34,r:2.1*power,color:'rgba(255,213,104,.85)'}); const colors=['#e6b24d','#8f2319','#352014','#f3dfb2','#6f8b42']; for(let i=0;i<34*power;i++){ state.fragments.push({x,y,vx:(Math.random()-.5)*16*power,vy:(Math.random()-.75)*12*power,r:3+Math.random()*9,life:45+Math.random()*55,max:100,spin:Math.random()*6,rs:(Math.random()-.5)*.5,color:colors[i%colors.length]}); } telemetry.rec('explosion',{x,y,power,label}); }
function damageTarget(t,a){ t.hp--; telemetry.rec('target.hit',{target:t.id,hp:t.hp,arrow:a}); if(t.hp<=0){ t.alive=false; explode(t.x,t.y,1.35,'target'); flash(''); telemetry.rec('target.destroyed',{target:t.id}); checkWin(); } else { explode(t.x,t.y,.42,'target.damage'); }}
function damageBowman(b,a){ b.hp--; explode(b.x,b.y-45,.65,'bowman.hit'); telemetry.rec('bowman.hit',{name:b.name,hp:b.hp,arrow:a}); if(b.hp<=0){ explode(b.x,b.y-36,1.25,'bowman.down'); flash(''); setTimeout(()=> b===player?loadLevel(state.level):completeLevel(),800); } else state.turn=b===player?'player':'enemy'; }
function hitGround(a){ a.dead=true; explode(a.x,groundY-4,.22,'ground'); telemetry.rec('arrow.ground',{arrow:a}); state.turn=(enemy&&a.owner==='player')?'enemy':'player'; }
function checkWin(){ if(targets.every(t=>!t.alive)){ if(enemy && enemy.hp>0){ state.turn='enemy'; } else completeLevel(); }}
function completeLevel(){ if(state.levelComplete)return; state.levelComplete=true; telemetry.rec('level.complete',{level:state.level}); setTimeout(()=>loadLevel((state.level+1)%LEVELS.length),900); }
function shoot(owner,vx,vy){ const b=owner==='player'?player:enemy; if(!b)return; const a={id:crypto.randomUUID(),owner,x:b.x+(owner==='player'?48:-48),y:b.y-36,vx,vy,buildId:BUILD_ID,shot:++state.shots}; state.arrows.push(a); telemetry.rec('arrow.shot',a); }
function enemyShoot(){ if(state.turn!=='enemy'||!enemy)return; state.aiQueued=false; const skill=enemy.skill; const target=player; const dx=target.x-enemy.x, dy=(target.y-38)-(enemy.y-36); const speed=14+skill*8; const angle=Math.atan2(dy,dx)-.30+(Math.random()-.5)*(1-skill)*.65; shoot('enemy',Math.cos(angle)*speed,Math.sin(angle)*speed); state.turn='player'; telemetry.rec('enemy.shoot',{enemy:enemy.name,skill}); }
function pointer(e){const r=canvas.getBoundingClientRect(); return {x:e.clientX-r.left,y:e.clientY-r.top};}
canvas.addEventListener('pointerdown',e=>{ canvas.setPointerCapture(e.pointerId); const p=pointer(e); telemetry.rec('pointer.down',p); const bp={x:wx(player.x+44),y:wy(player.y-36)}; if(Math.hypot(p.x-bp.x,p.y-bp.y)<110 && state.turn==='player'){ state.dragging=true; state.dragStart=bp; state.dragNow=p; }});
canvas.addEventListener('pointermove',e=>{ const p=pointer(e); if(state.dragging){ state.dragNow=p; if((performance.now()%80)<18) telemetry.rec('pointer.drag',p); }});
canvas.addEventListener('pointerup',e=>{ const p=pointer(e); telemetry.rec('pointer.up',p); if(!state.dragging)return; const dx=state.dragStart.x-p.x, dy=state.dragStart.y-p.y; const force=Math.min(30,Math.hypot(dx,dy)/9); const ang=Math.atan2(dy,dx); shoot('player',Math.cos(ang)*force,Math.sin(ang)*force); state.dragging=false; state.turn=enemy?'enemy':'player'; });
canvas.addEventListener('wheel',e=>{ e.preventDefault(); state.zoom=Math.max(.72,Math.min(1.85,state.zoom+(e.deltaY<0?.08:-.08))); telemetry.rec('zoom.wheel',{zoom:state.zoom}); },{passive:false});
function openMenu(){ menuPanel.classList.add('open'); menuPanel.setAttribute('aria-hidden','false'); menuButton.setAttribute('aria-expanded','true'); telemetry.rec('menu.open'); }
function closeMenu(){ menuPanel.classList.remove('open'); menuPanel.setAttribute('aria-hidden','true'); menuButton.setAttribute('aria-expanded','false'); telemetry.rec('menu.close'); }
menuButton.onclick=openMenu; $('closeMenu').onclick=closeMenu; $('zoomIn').onclick=()=>{state.zoom=Math.min(1.85,state.zoom+.12);telemetry.rec('zoom.button',{zoom:state.zoom})}; $('zoomOut').onclick=()=>{state.zoom=Math.max(.72,state.zoom-.12);telemetry.rec('zoom.button',{zoom:state.zoom})};
$('fullscreen').onclick=async()=>{ try{ await document.documentElement.requestFullscreen({navigationUI:'hide'}); telemetry.rec('fullscreen.enter'); closeMenu(); }catch(e){ telemetry.rec('fullscreen.error',{message:e.message}); }};
$('installIOS').onclick=()=>{ $('installHelp').hidden=!$('installHelp').hidden; telemetry.rec('install.ios.help',{visible:!$('installHelp').hidden,standalone:matchMedia('(display-mode: standalone)').matches}); };
$('logs').onclick=()=>{ const blob=new Blob([JSON.stringify(telemetry.dump(),null,2)],{type:'application/json'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=`${BUILD_ID}-telemetry.json`; a.click(); telemetry.rec('logs.download'); };
if('serviceWorker' in navigator){ addEventListener('load',()=>navigator.serviceWorker.register('./sw.js?v='+BUILD_ID).then(r=>telemetry.rec('sw.registered',{scope:r.scope})).catch(e=>telemetry.rec('sw.error',{message:e.message}))); }
window.Bloodwood={BUILD_ID,LEVELS,state,telemetry,loadLevel,openMenu,closeMenu};
