/* Bloodwood Bowmen: True Rivals */
const BUILD_ID = "bloodwood-bowmen-v20260620-0759-true-rivals";
const LEVELS = [
  {name:"Moonlit Butts", mode:"targets", wind:0.002, targets:[{x:680,y:.62,r:34,hp:2},{x:820,y:.50,r:28,hp:2},{x:970,y:.66,r:36,hp:3}]},
  {name:"Cinder Orchard", mode:"targets", wind:-0.012, targets:[{x:720,y:.64,r:42,hp:4},{x:925,y:.45,r:30,hp:3},{x:1110,y:.68,r:34,hp:4},{x:1260,y:.54,r:28,hp:3}]},
  {name:"Rook Duel", mode:"duel", wind:0.014, enemy:{x:980,skill:.40,hp:3,name:"Rafe Holt"}, targets:[{x:820,y:.61,r:24,hp:2},{x:1110,y:.55,r:26,hp:2}]},
  {name:"Glass Fen", mode:"duel", wind:-0.022, enemy:{x:1080,skill:.58,hp:4,name:"Mara Voss"}, targets:[{x:770,y:.56,r:28,hp:3},{x:940,y:.69,r:26,hp:3},{x:1210,y:.49,r:24,hp:3}]},
  {name:"Rainline", mode:"duel", wind:0.027, enemy:{x:1160,skill:.74,hp:5,name:"Ilan Greaves"}, targets:[{x:900,y:.47,r:24,hp:3},{x:1030,y:.65,r:28,hp:3}]},
  {name:"The Yew King", mode:"duel", wind:-0.034, enemy:{x:1250,skill:.88,hp:6,name:"The Yew King"}, targets:[{x:860,y:.58,r:26,hp:4},{x:1110,y:.45,r:24,hp:4},{x:1340,y:.66,r:30,hp:4}]}
];
const canvas = document.getElementById('game');
const ctx = canvas.getContext('2d');
const $ = id => document.getElementById(id);
const menuButton=$('menuButton'), menuPanel=$('menuPanel'), levelGrid=$('levelGrid');
const uuid=()=> (crypto && crypto.randomUUID) ? crypto.randomUUID() : `${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`;
const state = { level:0, zoom:1, cameraX:0, cameraTargetX:0, cameraFocus:'player', cameraShake:0, dragging:false, dragStart:null, dragNow:null, dragLast:null, dragTravel:0, dragMode:'pull', aimDir:null, arrows:[], fragments:[], shocks:[], popups:[], turn:'player', shots:0, last:0, aiQueued:false, levelComplete:false, aimPulse:0, banner:null };
let dpr=1,W=0,H=0,groundY=0,player,enemy,targets=[];
const telemetry = (()=>{ const sid=uuid(); const q=[]; function rec(type,data={}){ const evt={buildId:BUILD_ID,sessionId:sid,t:new Date().toISOString(),ms:Math.round(performance.now()),type,level:state.level,turn:state.turn,data}; q.push(evt); try{localStorage.setItem('bloodwood.runtimeTelemetry',JSON.stringify(q.slice(-1000)))}catch{} } addEventListener('error',e=>rec('window.error',{message:e.message,source:e.filename,line:e.lineno,col:e.colno})); addEventListener('unhandledrejection',e=>rec('promise.rejection',{reason:String(e.reason)})); return {rec,dump:()=>q.slice(),sid}; })();
telemetry.rec('boot',{ua:navigator.userAgent,viewport:[innerWidth,innerHeight],standalone:matchMedia('(display-mode: standalone)').matches});
function resize(){ dpr=Math.min(devicePixelRatio||1,2.5); W=Math.max(1,innerWidth); H=Math.max(1,innerHeight); canvas.width=Math.floor(W*dpr); canvas.height=Math.floor(H*dpr); ctx.setTransform(dpr,0,0,dpr,0,0); groundY=Math.max(245,H*.76); if(player)player.y=groundY-58; if(enemy)enemy.y=groundY-58; targets.forEach(t=>t.y=targetY(t)); telemetry.rec('resize',{W,H,dpr}); }
addEventListener('resize',resize,{passive:true}); addEventListener('orientationchange',()=>setTimeout(resize,250),{passive:true}); resize();
function targetY(t){ return typeof t.ySpec==='number' ? Math.round(H*t.ySpec) : t.y; }
function makeLevels(){ levelGrid.innerHTML=''; LEVELS.forEach((L,i)=>{ const b=document.createElement('button'); b.type='button'; b.className='levelBtn'; b.innerHTML=`<small>${String(i+1).padStart(2,'0')} · ${L.mode}</small><span>${L.name}</span>`; onTap(b,()=>{loadLevel(i); closeMenu();}); levelGrid.appendChild(b); }); }
function updateLevelButtons(){ [...levelGrid.children].forEach((b,i)=>b.classList.toggle('active',i===state.level)); }
function loadLevel(i){ const L=LEVELS[(i+LEVELS.length)%LEVELS.length]; state.level=(i+LEVELS.length)%LEVELS.length; state.arrows=[]; state.fragments=[]; state.shocks=[]; state.popups=[]; state.turn='player'; state.shots=0; state.aiQueued=false; state.levelComplete=false; state.banner={text:L.name,sub:L.mode==='duel'?'Duel: drop the rival or clear the field':'Break every mark',life:105,max:105}; player={x:145,y:groundY-58,hp:5,maxHp:5,name:'You',hitT:0}; enemy=L.enemy?{x:L.enemy.x,y:groundY-58,hp:L.enemy.hp,maxHp:L.enemy.hp,skill:L.enemy.skill,name:L.enemy.name,hitT:0}:null; targets=L.targets.map((t,k)=>({...t,ySpec:t.y,y:Math.round(H*t.y),maxHp:t.hp,id:`L${state.level}-T${k}`,alive:true})); state.cameraX=0; state.cameraTargetX=0; state.cameraFocus='player'; state.cameraShake=0; state.zoom=1; updateLevelButtons(); telemetry.rec('level.load',{index:state.level,level:L}); }
makeLevels(); loadLevel(0);
function wx(x){return (x-state.cameraX)*state.zoom + (state.cameraShake?(Math.random()-.5)*state.cameraShake:0)} function wy(y){return y*state.zoom+(H-H*state.zoom)*.5 + (state.cameraShake?(Math.random()-.5)*state.cameraShake*.55:0)}
function line(a,b,c,d){ctx.beginPath();ctx.moveTo(a,b);ctx.lineTo(c,d);ctx.stroke()} function blob(x,y,w,h,rot=0){ctx.beginPath();ctx.ellipse(x,y,w,h,rot,0,Math.PI*2);ctx.fill()} function dist(a,t){return Math.hypot(a.x-t.x,a.y-t.y)}
function loop(ts){ const dt=Math.min(34,ts-state.last||16)/16; state.last=ts; update(dt); draw(ts); requestAnimationFrame(loop); } requestAnimationFrame(loop);
function clamp(v,a,b){return Math.max(a,Math.min(b,v));}
function worldMaxX(){ return Math.max(1300,...targets.map(t=>t.x+160),enemy?enemy.x+260:0); }
function updateCamera(dt){ const active=state.arrows.length?state.arrows[state.arrows.length-1]:null; let focusX=player?player.x:0; state.cameraFocus='player'; if(active){ focusX=active.x + (active.vx>0?155:-155); state.cameraFocus=`arrow.${active.owner}`; } else if(state.turn==='enemy'&&enemy){ focusX=(player.x+enemy.x)/2; state.cameraFocus='duel'; } const maxX=Math.max(0,worldMaxX()-W/state.zoom+80); state.cameraTargetX=clamp(focusX-W/(state.zoom*2),0,maxX); state.cameraX+=(state.cameraTargetX-state.cameraX)*Math.min(1,.095*dt); state.cameraShake=Math.max(0,state.cameraShake-dt*.72); }
function update(dt){ const L=LEVELS[state.level]; for(const a of state.arrows){ if(a.dead)continue; a.vx+=L.wind*dt; a.vy+=.335*dt; a.x+=a.vx*dt; a.y+=a.vy*dt; if(a.y>groundY-4) hitGround(a); for(const t of targets){ if(!a.dead && a.owner==='player' && t.alive && dist(a,t)<t.r){ damageTarget(t,a); a.dead=true; }} if(enemy && !a.dead && a.owner==='player' && Math.hypot(a.x-enemy.x,a.y-(enemy.y-36))<34){ damageBowman(enemy,a); a.dead=true; } if(!a.dead && a.owner==='enemy' && Math.hypot(a.x-player.x,a.y-(player.y-36))<34){ damageBowman(player,a); a.dead=true; }} state.arrows=state.arrows.filter(a=>!a.dead && a.x>-360 && a.x<worldMaxX()+420 && a.y<1200); for(const p of state.fragments){ p.vy+=.18*dt; p.x+=p.vx*dt; p.y+=p.vy*dt; p.spin+=p.rs*dt; p.life-=dt; } state.fragments=state.fragments.filter(p=>p.life>0); for(const s of state.shocks)s.life-=dt; state.shocks=state.shocks.filter(s=>s.life>0); for(const p of state.popups){ p.x+=p.vx*dt; p.y+=p.vy*dt; p.vy-=.018*dt; p.life-=dt; } state.popups=state.popups.filter(p=>p.life>0); if(player)player.hitT=Math.max(0,(player.hitT||0)-dt); if(enemy)enemy.hitT=Math.max(0,(enemy.hitT||0)-dt); if(state.banner) { state.banner.life-=dt; if(state.banner.life<=0)state.banner=null; } updateCamera(dt); if(enemy&&state.turn==='enemy'&&!state.aiQueued&&state.arrows.length===0){ state.aiQueued=true; setTimeout(enemyShoot,420); }}
function draw(ts){ ctx.clearRect(0,0,W,H); drawWorld(ts); targets.forEach(t=>drawTarget(t,ts)); drawArcher(player,true,ts); if(enemy) drawArcher(enemy,false,ts); state.arrows.forEach(drawArrow); state.fragments.forEach(drawFragment); state.shocks.forEach(drawShock); state.popups.forEach(drawPopup); if(state.dragging) drawAim(ts); drawGlyphHUD(ts); drawBanner(); }
function drawWorld(ts){ const sky=ctx.createLinearGradient(0,0,0,H); sky.addColorStop(0,'#070812'); sky.addColorStop(.30,'#211936'); sky.addColorStop(.55,'#6f3a36'); sky.addColorStop(.72,'#19220f'); sky.addColorStop(1,'#070403'); ctx.fillStyle=sky; ctx.fillRect(0,0,W,H); ctx.globalAlpha=.8; ctx.fillStyle='#ffe8b7'; blob(W*.72,H*.16,44,44); ctx.globalAlpha=.16; ctx.fillStyle='#f9dd9e'; for(let i=-1;i<8;i++) blob(wx(i*260+80),wy(58+(i%3)*24),92,20); ctx.globalAlpha=1; for(let x=-160;x<1680;x+=88){ const trunk=wx(x), g=wy(groundY); ctx.strokeStyle='rgba(18,10,8,.86)'; ctx.lineWidth=8*state.zoom; line(trunk,g,trunk+18*state.zoom,g-(92+22*Math.sin(x))*state.zoom); ctx.fillStyle='rgba(21,27,13,.72)'; blob(trunk+18*state.zoom,g-112*state.zoom,40*state.zoom,28*state.zoom,.2); } const g=wy(groundY); ctx.fillStyle='#211109'; ctx.fillRect(0,g,W,H-g); ctx.fillStyle='#110907'; for(let x=-200;x<1700;x+=58) ctx.fillRect(wx(x),g-3,34*state.zoom,6); }
function drawArcher(b,isPlayer,ts){ const x=wx(b.x), y=wy(b.y), scale=state.zoom, hit=b.hitT||0; ctx.save(); ctx.translate(x+(isPlayer?-hit:hit)*.9,y-hit*.15); if(hit){ ctx.rotate((isPlayer?-1:1)*Math.sin(hit)*.055); ctx.shadowColor='rgba(255,70,44,.95)'; ctx.shadowBlur=18; } if(!isPlayer)ctx.scale(-1,1); ctx.scale(scale,scale); const breath=Math.sin(ts/410+b.x)*1.3; ctx.lineCap='round'; ctx.lineJoin='round'; ctx.fillStyle='rgba(0,0,0,.42)'; blob(0,13,48,10); ctx.strokeStyle='#17100d'; ctx.lineWidth=9; line(-8,-42+breath,-13,-4); line(10,-42+breath,8,-4); ctx.strokeStyle=isPlayer?'#6a4730':'#3d3345'; line(-10,-5,-28,44); line(8,-5,23,44); ctx.strokeStyle='#140d0b'; ctx.lineWidth=6; line(-28,44,-41,48); line(23,44,36,47); const coat=ctx.createLinearGradient(-20,-70,22,0); coat.addColorStop(0,isPlayer?'#24170f':'#17131d'); coat.addColorStop(1,hit?'#d04a2d':(isPlayer?'#8a623d':'#6c587d')); ctx.fillStyle=coat; ctx.beginPath(); ctx.moveTo(-22,-56+breath); ctx.quadraticCurveTo(0,-80+breath,24,-55+breath); ctx.lineTo(16,-8); ctx.quadraticCurveTo(0,5,-18,-8); ctx.closePath(); ctx.fill(); if(hit){ ctx.globalAlpha=.72; ctx.fillStyle='#ffd78d'; blob(10,-54,18+hit*.5,7+hit*.18,.25); ctx.globalAlpha=1; } ctx.fillStyle=isPlayer?'#c18e62':'#9f7669'; blob(0,-85+breath,13,16); ctx.fillStyle='#140e0a'; blob(0,-99+breath,16,7,.15); ctx.strokeStyle='#20130e'; ctx.lineWidth=7; line(-13,-48+breath,-43,-33); line(15,-47+breath,36,-35); ctx.strokeStyle='#d0a35b'; ctx.lineWidth=4; ctx.beginPath(); ctx.arc(45,-32,45,-1.35,1.35); ctx.stroke(); ctx.strokeStyle='rgba(255,240,201,.86)'; ctx.lineWidth=1.4; line(56,-74,56,10); ctx.fillStyle='#ba3329'; for(let i=0;i<b.hp;i++) blob(-31+i*11,-119,4.4,5.4); ctx.restore(); }
function drawTarget(t,ts){ if(!t.alive)return; const x=wx(t.x), y=wy(t.y), r=t.r*state.zoom, frac=t.hp/t.maxHp; ctx.save(); ctx.translate(x,y); ctx.rotate(Math.sin(ts/380+t.x)*.025+(1-frac)*.08); ctx.fillStyle='#281309'; ctx.fillRect(-r*.12,r*.72,r*.24,wy(groundY)-y-r*.72); ctx.shadowColor='rgba(255,106,61,.22)'; ctx.shadowBlur=18; ctx.fillStyle='#33170f'; blob(0,0,r*1.1,r*1.1); ctx.fillStyle=`hsl(${30+frac*58},58%,${31+frac*22}%)`; blob(0,0,r*.9,r*.9); ctx.fillStyle='#f1dbad'; blob(0,0,r*.6,r*.6); ctx.fillStyle='#a3241c'; blob(0,0,r*.31,r*.31); ctx.shadowBlur=0; ctx.strokeStyle='rgba(8,3,2,.82)'; ctx.lineWidth=2.4; for(let i=0;i<t.maxHp-t.hp;i++) line(-r*.72+i*r*.20,-r*.38,r*.16+i*r*.08,r*.54); ctx.restore(); }
function drawArrow(a){ ctx.save(); ctx.translate(wx(a.x),wy(a.y)); ctx.rotate(Math.atan2(a.vy,a.vx)); ctx.strokeStyle='#2b1a0e'; ctx.lineWidth=Math.max(2,3*state.zoom); line(-22*state.zoom,0,18*state.zoom,0); ctx.fillStyle='#e7d6b5'; ctx.beginPath(); ctx.moveTo(21*state.zoom,0); ctx.lineTo(8*state.zoom,-5*state.zoom); ctx.lineTo(8*state.zoom,5*state.zoom); ctx.closePath(); ctx.fill(); ctx.fillStyle=a.owner==='player'?'#e9bb5e':'#b69cff'; ctx.fillRect(-23*state.zoom,-3*state.zoom,9*state.zoom,6*state.zoom); ctx.restore(); }
function drawFragment(p){ ctx.save(); ctx.translate(wx(p.x),wy(p.y)); ctx.rotate(p.spin); ctx.globalAlpha=Math.max(0,p.life/p.max); ctx.fillStyle=p.color; blob(0,0,p.r*state.zoom,p.r*.62*state.zoom); ctx.restore(); ctx.globalAlpha=1; }
function drawShock(s){ ctx.save(); ctx.globalAlpha=Math.max(0,s.life/s.max); ctx.strokeStyle=s.color; ctx.lineWidth=3*state.zoom; ctx.beginPath(); ctx.arc(wx(s.x),wy(s.y),(s.max-s.life)*s.r*state.zoom,0,Math.PI*2); ctx.stroke(); ctx.restore(); ctx.globalAlpha=1; }
function drawPopup(p){ ctx.save(); const a=Math.max(0,p.life/p.max); ctx.globalAlpha=a; ctx.font=`${Math.round((18+p.size)*state.zoom)}px ui-sans-serif, system-ui`; ctx.lineWidth=4; ctx.strokeStyle='rgba(0,0,0,.72)'; ctx.fillStyle=p.color||'#ffe2a5'; ctx.textAlign='center'; ctx.strokeText(p.text,wx(p.x),wy(p.y)); ctx.fillText(p.text,wx(p.x),wy(p.y)); ctx.restore(); ctx.globalAlpha=1; }
function drawBanner(){ if(!state.banner)return; const b=state.banner, a=clamp(b.life/34,0,1); ctx.save(); ctx.globalAlpha=Math.min(.96,a); ctx.fillStyle='rgba(0,0,0,.36)'; ctx.fillRect(W*.22,H*.10,W*.56,72); ctx.strokeStyle='rgba(255,210,122,.55)'; ctx.strokeRect(W*.22,H*.10,W*.56,72); ctx.textAlign='center'; ctx.fillStyle='#ffe0a1'; ctx.font='900 26px ui-sans-serif, system-ui'; ctx.fillText(b.text,W*.5,H*.10+31); ctx.fillStyle='#d2b16f'; ctx.font='700 14px ui-sans-serif, system-ui'; ctx.fillText(b.sub,W*.5,H*.10+54); ctx.restore(); }
function drawAim(ts){ const start={x:wx(player.x+46),y:wy(player.y-36)}, cur=state.dragNow; const dir=state.aimDir||{x:1,y:0}; const pull=state.dragMode==='line'?Math.min(260,state.dragTravel):Math.hypot(start.x-cur.x,start.y-cur.y); const glow=Math.min(1,pull/230); ctx.save(); ctx.strokeStyle=`rgba(255,${Math.round(190+45*glow)},${Math.round(115+55*glow)},.94)`; ctx.lineWidth=3+3*glow; ctx.setLineDash([12,8]); line(start.x,start.y,start.x+dir.x*(220+pull*.55),start.y+dir.y*(220+pull*.55)); ctx.setLineDash([]); ctx.fillStyle='rgba(255,93,52,.92)'; blob(cur.x,cur.y,10+Math.sin(ts/80)*2+glow*6,10+glow*4); ctx.globalAlpha=.35+.45*glow; ctx.strokeStyle='#ffd980'; ctx.lineWidth=2; ctx.beginPath(); ctx.arc(start.x,start.y,24+pull*.12,0,Math.PI*2); ctx.stroke(); ctx.restore(); }
function drawGlyphHUD(ts){ const L=LEVELS[state.level]; ctx.save(); ctx.globalAlpha=.82; ctx.fillStyle='rgba(0,0,0,.25)'; blob(W-56,H-42,38,16); ctx.strokeStyle='#e7c277'; ctx.lineWidth=3; line(W-78,H-42,W-38,H-42); const dir=L.wind>=0?1:-1; line(W-58+dir*18,H-48,W-38,H-42); ctx.restore(); }
function popText(text,x,y,color='#ffe2a5',size=5){ state.popups.push({text,x,y,vx:(Math.random()-.5)*2.8,vy:-2.2-Math.random()*1.4,life:44,max:44,color,size}); }
function explode(x,y,power=1,label='target'){ state.cameraShake=Math.max(state.cameraShake,7*power); state.shocks.push({x,y,life:34,max:34,r:2.25*power,color:'rgba(255,196,90,.86)'}); const colors=['#ffbe55','#f05a32','#2a140d','#f4dfb4','#6f8b42']; for(let i=0;i<36*power;i++) state.fragments.push({x,y,vx:(Math.random()-.5)*17*power,vy:(Math.random()-.78)*13*power,r:3+Math.random()*9,life:45+Math.random()*58,max:103,spin:Math.random()*6,rs:(Math.random()-.5)*.55,color:colors[i%colors.length]}); telemetry.rec('explosion',{x,y,power,label}); }
function damageTarget(t,a){ t.hp--; popText(t.hp<=0?'SHATTER':'hit',t.x,t.y-t.r,'#ffd26d',t.hp<=0?11:3); telemetry.rec('target.hit',{target:t.id,hp:t.hp}); if(t.hp<=0){ t.alive=false; explode(t.x,t.y,1.38,'target'); telemetry.rec('target.destroyed',{target:t.id}); checkWin(); } else explode(t.x,t.y,.45,'target.damage'); }
function damageBowman(b,a){ b.hp--; b.hitT=22; state.cameraShake=Math.max(state.cameraShake,12); popText(b===player?'YOU HIT':'RIVAL HIT',b.x,b.y-86,b===player?'#ff8468':'#ffe06f',8); explode(b.x,b.y-45,.92,'bowman.hit'); telemetry.rec('bowman.hit',{name:b.name,hp:b.hp,owner:a&&a.owner}); if(b.hp<=0){ popText(b===player?'FALLEN':'LEVEL WON',b.x,b.y-112,b===player?'#ff5d4a':'#fff0a5',13); explode(b.x,b.y-36,1.55,'bowman.down'); setTimeout(()=> b===player?loadLevel(state.level):completeLevel(),800); } else state.turn=b===player?'player':'enemy'; }
function hitGround(a){ a.dead=true; explode(a.x,groundY-4,.22,'ground'); telemetry.rec('arrow.ground',{}); state.turn=(enemy&&a.owner==='player')?'enemy':'player'; }
function checkWin(){ if(targets.every(t=>!t.alive)){ if(enemy && enemy.hp>0) state.turn='enemy'; else completeLevel(); }}
function completeLevel(){ if(state.levelComplete)return; state.levelComplete=true; state.banner={text:'Level defeated',sub:'Moving to the next line...',life:72,max:72}; telemetry.rec('level.complete',{level:state.level,next:(state.level+1)%LEVELS.length}); setTimeout(()=>loadLevel((state.level+1)%LEVELS.length),900); }
function shoot(owner,vx,vy){ const b=owner==='player'?player:enemy; if(!b)return; state.arrows.push({id:uuid(),owner,x:b.x+(owner==='player'?48:-48),y:b.y-36,vx,vy,buildId:BUILD_ID,shot:++state.shots}); telemetry.rec('arrow.shot',{owner,vx,vy,shot:state.shots}); }
function enemyAimSolution(){ const L=LEVELS[state.level], difficulty=state.level/(LEVELS.length-1), skill=enemy.skill, accuracy=clamp(skill*.72+difficulty*.28,.18,.96); const dx=player.x-48-enemy.x, baseY=player.y-38, speed=17+skill*8+difficulty*4; let t=clamp(Math.abs(dx)/speed,32,76); const sigma=190-accuracy*140, nearMiss=Math.random()<(.12+(1-accuracy)*.20); const errScale=nearMiss?1.8:1; const errX=(Math.random()+Math.random()+Math.random()-1.5)*sigma*errScale; const errY=(Math.random()+Math.random()+Math.random()-1.5)*sigma*.58*errScale; const tx=player.x+errX, ty=baseY+errY; const vx=(tx-(enemy.x-48)-0.5*L.wind*t*t)/t; const vy=(ty-(enemy.y-36)-0.5*.335*t*t)/t; return {vx,vy,skill,difficulty,accuracy,errX:Math.round(errX),errY:Math.round(errY),nearMiss,t:Math.round(t),target:{x:Math.round(tx),y:Math.round(ty)}}; }
function enemyShoot(){ if(state.turn!=='enemy'||!enemy)return; state.aiQueued=false; const aim=enemyAimSolution(); shoot('enemy',aim.vx,aim.vy); state.turn='player'; telemetry.rec('enemy.shoot',{enemy:enemy.name,...aim}); }
function pointFromEvent(e){ const src=e.touches?e.touches[0]:(e.changedTouches?e.changedTouches[0]:e); const r=canvas.getBoundingClientRect(); return {x:src.clientX-r.left,y:src.clientY-r.top}; }
function norm(x,y){ const m=Math.hypot(x,y)||1; return {x:x/m,y:y/m}; }
function playerBowScreen(){ return {x:wx(player.x+46),y:wy(player.y-36)}; }
function drawForceFromTravel(px){ return Math.min(46, 8 + px/5.4); }
function startDrag(e){ if(e.cancelable)e.preventDefault(); const p=pointFromEvent(e); telemetry.rec('input.down',p); if(state.turn!=='player')return; const bp=playerBowScreen(); const fromBow=Math.hypot(p.x-bp.x,p.y-bp.y); const lineStart=fromBow>=128; state.dragging=true; state.dragStart=bp; state.dragNow=p; state.dragLast=p; state.dragTravel=lineStart?Math.min(180,fromBow*.32):0; state.dragMode=lineStart?'line':'pull'; state.aimDir=lineStart?norm(p.x-bp.x,p.y-bp.y):norm(bp.x-p.x,bp.y-p.y); telemetry.rec('draw.start',{mode:state.dragMode,fromBow,initialTravel:state.dragTravel}); }
function moveDrag(e){ if(!state.dragging)return; if(e.cancelable)e.preventDefault(); const p=pointFromEvent(e); state.dragTravel+=Math.hypot(p.x-state.dragLast.x,p.y-state.dragLast.y); state.dragLast=p; state.dragNow=p; if(state.dragMode==='pull') state.aimDir=norm(state.dragStart.x-p.x,state.dragStart.y-p.y); }
function endDrag(e){ if(e.cancelable)e.preventDefault(); const p=pointFromEvent(e); telemetry.rec('input.up',p); if(!state.dragging)return; state.dragTravel+=Math.hypot(p.x-state.dragLast.x,p.y-state.dragLast.y); if(state.dragMode==='pull') state.aimDir=norm(state.dragStart.x-p.x,state.dragStart.y-p.y); const travel=state.dragMode==='line'?state.dragTravel:Math.max(state.dragTravel,Math.hypot(state.dragStart.x-p.x,state.dragStart.y-p.y)); const force=drawForceFromTravel(travel); const dir=state.aimDir||{x:1,y:0}; telemetry.rec('draw.release',{mode:state.dragMode,travel,force,dir}); shoot('player',dir.x*force,dir.y*force); state.dragging=false; state.dragLast=null; state.dragTravel=0; state.turn=enemy?'enemy':'player'; }
if(window.PointerEvent){ canvas.addEventListener('pointerdown',e=>{ try{canvas.setPointerCapture(e.pointerId)}catch{}; startDrag(e); },{passive:false}); canvas.addEventListener('pointermove',moveDrag,{passive:false}); canvas.addEventListener('pointerup',endDrag,{passive:false}); canvas.addEventListener('pointercancel',()=>{state.dragging=false},{passive:true}); }
canvas.addEventListener('touchstart',startDrag,{passive:false}); canvas.addEventListener('touchmove',moveDrag,{passive:false}); canvas.addEventListener('touchend',endDrag,{passive:false}); canvas.addEventListener('mousedown',startDrag); addEventListener('mousemove',moveDrag); addEventListener('mouseup',endDrag);
canvas.addEventListener('wheel',e=>{ e.preventDefault(); state.zoom=Math.max(.72,Math.min(1.85,state.zoom+(e.deltaY<0?.08:-.08))); telemetry.rec('zoom.wheel',{zoom:state.zoom}); },{passive:false});
function onTap(el,fn){ let fired=false; el.addEventListener('touchend',e=>{ if(e.cancelable)e.preventDefault(); fired=true; fn(e); setTimeout(()=>fired=false,350); },{passive:false}); el.addEventListener('click',e=>{ if(!fired)fn(e); }); }
function openMenu(){ menuPanel.classList.add('open'); menuPanel.setAttribute('aria-hidden','false'); menuButton.setAttribute('aria-expanded','true'); telemetry.rec('menu.open'); }
function closeMenu(){ menuPanel.classList.remove('open'); menuPanel.setAttribute('aria-hidden','true'); menuButton.setAttribute('aria-expanded','false'); telemetry.rec('menu.close'); }
onTap(menuButton,openMenu); onTap($('closeMenu'),closeMenu); menuPanel.addEventListener('click',e=>{ if(e.target===menuPanel)closeMenu(); });
onTap($('zoomIn'),()=>{state.zoom=Math.min(1.85,state.zoom+.12);telemetry.rec('zoom.button',{zoom:state.zoom})}); onTap($('zoomOut'),()=>{state.zoom=Math.max(.72,state.zoom-.12);telemetry.rec('zoom.button',{zoom:state.zoom})});
onTap($('fullscreen'),async()=>{ try{ if(document.fullscreenElement) await document.exitFullscreen(); else if(document.documentElement.requestFullscreen) await document.documentElement.requestFullscreen({navigationUI:'hide'}); telemetry.rec('fullscreen.toggle'); closeMenu(); }catch(e){ telemetry.rec('fullscreen.error',{message:e.message}); closeMenu(); }});
onTap($('installIOS'),()=>{ $('installHelp').hidden=!$('installHelp').hidden; telemetry.rec('install.ios.help',{visible:!$('installHelp').hidden,standalone:matchMedia('(display-mode: standalone)').matches}); });
if('serviceWorker' in navigator){ addEventListener('load',()=>navigator.serviceWorker.register('./sw.js?v='+BUILD_ID).then(r=>{ r.update&&r.update(); telemetry.rec('sw.registered',{scope:r.scope}); }).catch(e=>telemetry.rec('sw.error',{message:e.message}))); }
window.Bloodwood={BUILD_ID,LEVELS,state,telemetry,loadLevel,openMenu,closeMenu};
