const fs = require('fs');
const assert = require('assert');
const js = fs.readFileSync('game.js','utf8');
const html = fs.readFileSync('index.html','utf8');
const manifest = fs.readFileSync('manifest.webmanifest','utf8');
const sw = fs.readFileSync('sw.js','utf8');
const build = 'bloodwood-bowmen-v20260620-0818-reserve-line';
assert(js.includes(build));
assert(html.includes(build));
assert(manifest.includes(build));
assert(sw.includes(build));
assert(!html.includes('Download Logs'));
assert(!js.includes('navigator.sendBeacon'));
assert(!js.includes('/api/log'));
assert(js.includes('runtimeTelemetry'));
assert(js.includes('drawForceFromTravel(px)'));
assert(js.includes('Math.min(46, 8 + px/5.4)'));
assert(js.includes("dragMode=lineStart?'line':'pull'"));
assert(js.includes("telemetry.rec('draw.release'"));
assert(js.includes('state.dragTravel+=Math.hypot'));
assert(js.includes('const DEFAULT_ZOOM = .58'));
assert(js.includes('MIN_ZOOM = .42'));
assert(js.includes('state.zoom=DEFAULT_ZOOM'));
assert(js.includes('enemyAimSolution()'));
assert(js.includes('accuracy=clamp(skill*.72+difficulty*.28'));
assert(js.includes('errX=(Math.random()+Math.random()+Math.random()-1.5)*sigma'));
assert(js.includes("telemetry.rec('enemy.shoot'"));
assert(js.includes('function updateCamera(dt)'));
assert(js.includes('cameraFocus=`arrow.${active.owner}`'));
assert(js.includes('state.cameraTargetX=clamp'));
assert(js.includes('state.popups=[]'));
assert(js.includes('function drawPopup(p)'));
assert(js.includes('b.hitT=22'));
assert(js.includes("popText(b===player?'YOU HIT':'RIVAL HIT'"));
assert(js.includes("state.banner={text:'Level defeated'"));
assert(js.includes('setTimeout(()=>loadLevel((state.level+1)%LEVELS.length),900)'));
assert(js.includes('for(const t of targets){ if(!a.dead && a.owner===\'player\' && t.alive'));
assert(js.includes('mode:"line"'));
assert(js.includes('playerLine:[') && js.includes('enemyLine:['));
assert(js.includes('function spawnPlayer(spec'));
assert(js.includes('function spawnEnemy(spec'));
assert(js.includes("telemetry.rec('player.replaced'"));
assert(js.includes("telemetry.rec('enemy.replaced'"));
assert(js.includes("L.mode==='line' && state.playerReserve.length"));
assert(js.includes("L.mode==='line' && state.enemyReserve.length"));
assert(!js.includes('mode:"duel", wind:0.014, enemy:{x:980,skill:.40,hp:3,name:"Rafe Holt"}, targets:[{'));
assert((js.match(/mode:\"duel\"[^\n]+targets:\[\]/g)||[]).length >= 4);
assert(js.includes('touchstart') && js.includes('touchend') && js.includes('PointerEvent') && js.includes('mousedown'));
assert(js.includes('onTap(menuButton,openMenu)') && js.includes("onTap($('closeMenu'),closeMenu)"));
assert(js.includes('requestFullscreen'));
assert(js.includes('serviceWorker.register'));
assert(js.includes('r.update&&r.update'));
assert(sw.includes("cache:'no-store'"));
assert(sw.includes("k.startsWith('bloodwood-bowmen-')"));
assert(js.includes('explode(') && js.includes("telemetry.rec('explosion'"));
assert((js.match(/mode:\"duel\"/g)||[]).length >= 4);
assert((js.match(/mode:\"targets\"/g)||[]).length >= 2);
assert((js.match(/mode:\"line\"/g)||[]).length >= 1);
assert(js.includes('levelGrid'));
assert(html.includes('All levels open'));
assert(html.includes('id="menuButton"') && !html.includes('id="hud"'));
assert(html.includes('apple-mobile-web-app-capable'));
const m = JSON.parse(manifest);
assert.equal(m.display, 'fullscreen');
assert.equal(m.orientation, 'landscape');
assert(m.icons.some(i => i.sizes === '512x512'));
console.log('ok: v6 reserve-line build, zoomed-out start, pure duel levels without target shields, replacement fighters, camera/AI/feedback/progression hooks');
