const fs = require('fs');
const assert = require('assert');
const js = fs.readFileSync('game.js','utf8');
const html = fs.readFileSync('index.html','utf8');
const manifest = fs.readFileSync('manifest.webmanifest','utf8');
const sw = fs.readFileSync('sw.js','utf8');
const build = 'bloodwood-bowmen-v20260620-0132-night-orchard';
assert(js.includes(build));
assert(html.includes(build));
assert(manifest.includes(build));
assert(sw.includes(build));
assert(!html.includes('Download Logs'));
assert(!js.includes('navigator.sendBeacon'));
assert(!js.includes('/api/log'));
assert(js.includes('runtimeTelemetry'));
assert(js.includes('touchstart') && js.includes('touchend') && js.includes('PointerEvent') && js.includes('mousedown'));
assert(js.includes('onTap(menuButton,openMenu)') && js.includes("onTap($('closeMenu'),closeMenu)"));
assert(js.includes('requestFullscreen'));
assert(js.includes('serviceWorker.register'));
assert(js.includes('r.update&&r.update'));
assert(sw.includes("cache:'no-store'"));
assert(sw.includes("k.startsWith('bloodwood-bowmen-')"));
assert(js.includes('explode(') && js.includes("telemetry.rec('explosion'"));
assert((js.match(/mode:\"duel\"/g)||[]).length >= 4);
assert((js.match(/mode:\"targets\"/g)||[]).length >= 2);
assert(js.includes('levelGrid'));
assert(html.includes('All levels open'));
assert(html.includes('id="menuButton"') && !html.includes('id="hud"'));
assert(html.includes('apple-mobile-web-app-capable'));
const m = JSON.parse(manifest);
assert.equal(m.display, 'fullscreen');
assert.equal(m.orientation, 'landscape');
assert(m.icons.some(i => i.sizes === '512x512'));
console.log('ok: v3 night-orchard build, no game log UI, robust iOS touch/menu/PWA, open duel levels, explosions, visual refresh hooks');
